# Generated by Django 3.0 on 2020-04-19 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles_api', '0002_classprofilefeeditem'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassProfileFeedItem',
            new_name='ProfileFeedItem',
        ),
    ]
